-- MySQL Script generated by MySQL Workbench
-- Thu Jun 27 15:01:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zamppet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zamppet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zamppet` DEFAULT CHARACTER SET utf8 ;
USE `zamppet` ;

-- -----------------------------------------------------
-- Table `zamppet`.`funcionarios_cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zamppet`.`funcionarios_cargos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zamppet`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zamppet`.`funcionarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `funcionarios_cargos_id` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(11) NULL DEFAULT NULL,
  `cargo` VARCHAR(45) NULL DEFAULT NULL,
  `data_admissao` DATE NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `funcionarios_cargos_id`),
  INDEX `fk_funcionarios_funcionarios_cargos1_idx` (`funcionarios_cargos_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionarios_funcionarios_cargos1`
    FOREIGN KEY (`funcionarios_cargos_id`)
    REFERENCES `zamppet`.`funcionarios_cargos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zamppet`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zamppet`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `endereco` VARCHAR(50) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `telefone` VARCHAR(14) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zamppet`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zamppet`.`pets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clientes_id` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `especie` VARCHAR(50) NOT NULL,
  `raca` VARCHAR(50) NOT NULL,
  `sexo` VARCHAR(50) NOT NULL,
  `dataNascimento` DATE NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `clientes_id`),
  INDEX `fk_pets_clientes_idx` (`clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_pets_clientes`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `zamppet`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zamppet`.`funcionarios_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zamppet`.`funcionarios_usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `funcionarios_id` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `funcionarios_id`),
  INDEX `fk_funcionarios_usuarios_funcionarios1_idx` (`funcionarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionarios_usuarios_funcionarios1`
    FOREIGN KEY (`funcionarios_id`)
    REFERENCES `zamppet`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zamppet`.`prontuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zamppet`.`prontuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pets_id` INT NOT NULL,
  PRIMARY KEY (`id`, `pets_id`),
  INDEX `fk_prontuarios_pets1_idx` (`pets_id` ASC) VISIBLE,
  UNIQUE INDEX `pets_id_UNIQUE` (`pets_id` ASC) VISIBLE,
  CONSTRAINT `fk_prontuarios_pets1`
    FOREIGN KEY (`pets_id`)
    REFERENCES `zamppet`.`pets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zamppet`.`prontuarios_registros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zamppet`.`prontuarios_registros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prontuarios_id` INT NOT NULL,
  `funcionarios_id` INT NOT NULL,
  `data_registro` DATE NOT NULL,
  `observacao` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_prontuarios_registros_prontuarios2`
    FOREIGN KEY (`prontuarios_id`)
    REFERENCES `zamppet`.`prontuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `zamppet`.`funcionarios_cargos`
-- -----------------------------------------------------
START TRANSACTION;
USE `zamppet`;
INSERT INTO `zamppet`.`funcionarios_cargos` (`id`, `cargo`) VALUES (1, 'GERENTE');
INSERT INTO `zamppet`.`funcionarios_cargos` (`id`, `cargo`) VALUES (2, 'VETERINARIO');
INSERT INTO `zamppet`.`funcionarios_cargos` (`id`, `cargo`) VALUES (3, 'RECEPCIONISTA');

COMMIT;


-- -----------------------------------------------------
-- Data for table `zamppet`.`funcionarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `zamppet`;
INSERT INTO `zamppet`.`funcionarios` (`id`, `funcionarios_cargos_id`, `nome`, `cpf`, `cargo`, `data_admissao`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, 1, 'ADMINISTRADOR', '00000000000', 'GERENTE', '1970-01-01', DEFAULT, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `zamppet`.`funcionarios_usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `zamppet`;
INSERT INTO `zamppet`.`funcionarios_usuarios` (`id`, `funcionarios_id`, `email`, `senha`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, 1, 'admin@zamppet.com', '$2y$10$Frsk/R2LtGxez1UPD9GpnuYLG9pWZSKkIDQsi.1CYYrvMy7XRD4Ri', DEFAULT, NULL, NULL);

COMMIT;